version: '3.6'

services:
  api_gateway:
    build:
      dockerfile: api_gateway/Dockerfile
    command:
      - ./docker-entrypoint.sh
    networks:
      - default
    ports:
      - "5000:5000"
  mom:
    build:
      dockerfile: mom/Dockerfile
    command:
      - ./docker-entrypoint.sh
    networks:
      - default
    ports:
      - "6000:6000"
