openapi: 3.0.3
info:
  title: Unified Availability Service ${stage}
  version: '1.0'
servers:
  - url: http://localhost:{port}
    description: Local development server
    variables:
      port:
        default: '5010'
  - url: https://unified-availability-service.api.qa.patientpop.com
    description: QA server
  - url: https://unified-availability-service.api.stg.patientpop.com
    description: Staging server
  - url: https://unified-availability-service.api.patientpop.com
    description: Production server
paths:
  /read_from_queue/{queue_name}:
    get:
      summary: read from queue
      parameters:
        - schema:
            type: string
          name: queue_name
          in: path
          required: true
      responses:
        '200':
          description: message from queue
          content:
            application/json: { }
        '404':
          description: queue not found
          content:
            application/json: { }
      description: Files available on server
      operationId: get_file_list
      x-openapi-router-controller: app.controllers
      tags:
        - file_list
  /post_to_queue/{queue_name}:
    post:
      summary: post message to queue
      parameters: []
      responses:
        '200':
          description: Message post to queue
          content:
            application/json: { }
        '424':
          description: Failed dependency MOM
          content:
            application/json: { }
      description: find file in server
      operationId: post_to_queue
      x-openapi-router-controller: app.controllers
      tags:
        - post_to_queue
  /create_to_queue/{queue_name}:
    post:
      summary: Create queue with name on mom
      parameters: []
      responses:
        '200':
          description: Queue created
          content:
            application/json: { }
        '424':
          description: Failed dependency MOM
          content:
            application/json: { }
      description: create-queue
      operationId: create_queue
      x-openapi-router-controller: app.controllers
      tags:
        - create_queue
