openapi: 3.0.3
info:
  title: Gateway Proyecto 1 - MOM
  version: '1.0'
servers:
  - url: http://localhost:{port}
    description: Gateway Local
    variables:
      port:
        default: '8000'
paths:
  /read_from_queue/{queue_name}:
    get:
      summary: read from queue
      parameters:
        - schema:
            type: string
          name: queue_name
          in: path
          required: true
      responses:
        '200':
          description: message from queue
          content:
            application/json: { }
        '404':
          description: queue not found
          content:
            application/json: { }
      description: Read message on queue
      operationId: read_from_queue
      x-openapi-router-controller: app.controllers
      tags:
        - read_from_queue
  /post_to_queue/{queue_name}:
    post:
      summary: post message to queue
      parameters: 
        - schema:
            type: string
          name: queue_name
          in: path
          required: true
      requestBody:
        description: payload for queue
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payload'
      responses:
        '200':
          description: Message post to queue
          content:
            application/json: {}
        '424':
          description: Failed dependency MOM
          content:
            application/json: { }
      description: post message to queue
      operationId: post_to_queue
      x-openapi-router-controller: app.controllers
      tags:
        - post_to_queue
  /create_queue/{queue_name}:
    post:
      summary: Create queue with name on mom
      parameters:
        - schema:
            type: string
          name: queue_name
          in: path
          required: true
      responses:
        '200':
          description: Queue created
          content:
            application/json: { }
        '424':
          description: Failed dependency MOM
          content:
            application/json: { }
      description: create-queue
      operationId: create_queue
      x-openapi-router-controller: app.controllers
      tags:
        - create_queue
  /delete_queue/{queue_name}:
    post:
      summary: Delete queue with name on mom
      parameters:
        - schema:
            type: string
          name: queue_name
          in: path
          required: true
      responses:
        '200':
          description: Queue deleted
          content:
            application/json: { }
        '424':
          description: Failed dependency MOM
          content:
            application/json: { }
      description: delete-queue
      operationId: delete_queue
      x-openapi-router-controller: app.controllers
      tags:
        - delete_queue
  /list_queues:
    get:
      summary: list queues
      responses:
        '200':
          description: list of available queues
          content:
            application/json: { }
        '404':
          description: queue not found
          content:
            application/json: { }
      description: List queues
      operationId: list_queues
      x-openapi-router-controller: app.controllers
      tags:
        - list_queues

components:
  schemas:
    Payload:
      additionalProperties: false
      type: object
      x-examples:
        ExamplePayload:
          data: "something"
      properties:
        data:
          type: string
      required:
        - data
      description: Payload to send to queue.