openapi: 3.0.3
info:
  title: Unified Availability Service ${stage}
  version: '1.0'
servers:
  - url: http://localhost:{port}
    description: Local development server
    variables:
      port:
        default: '5010'
  - url: https://unified-availability-service.api.qa.patientpop.com
    description: QA server
  - url: https://unified-availability-service.api.stg.patientpop.com
    description: Staging server
  - url: https://unified-availability-service.api.patientpop.com
    description: Production server