DROP TABLE IF EXISTS queue;

CREATE TABLE queue (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   name TEXT NOT NULL
);

CREATE TABLE topic (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   name TEXT NOT NULL
);
