# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import messages_pb2 as messages__pb2


class MessagesStub(object):
    """Definición del servicio para la lista de archivos y la búsqueda 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSendMessage = channel.unary_unary(
                '/Messages/GetSendMessage',
                request_serializer=messages__pb2.Message.SerializeToString,
                response_deserializer=messages__pb2.SendMessageResponse.FromString,
                )


class MessagesServicer(object):
    """Definición del servicio para la lista de archivos y la búsqueda 
    """

    def GetSendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessagesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSendMessage,
                    request_deserializer=messages__pb2.Message.FromString,
                    response_serializer=messages__pb2.SendMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Messages', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Messages(object):
    """Definición del servicio para la lista de archivos y la búsqueda 
    """

    @staticmethod
    def GetSendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Messages/GetSendMessage',
            messages__pb2.Message.SerializeToString,
            messages__pb2.SendMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
